sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tA46MYbmEdKJXHBBVat
    access-key-secret: N4YpGklKH6z4HncCM1IIXm3kd0gtzR
    bucket-name: sky-lqf
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10 # 不设置的话默认是0
  wechat:
    appid: wx799ca73e1c3b10ac
    secret: 36e9e611b028ad9c0fe54d52d1cd4106